[package]
name = "volumetric-fog"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15", features = [
  "jpeg",
  "ktx2",
  "png",
  "hdr",
  "default",
] }
bevy_rapier3d = { version = "0.29.0", features = ["simd-stable"] }
